[package]
name = "google_photos_fix_metadata"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.118"
chrono = "0.4.38"
walkdir = "2.5.0"
filetime = "0.2.23"
clap = "4.5.7"
regex = "1.10.5"
rand = "0.9.0-alpha.1"


